# Generated by Django 2.0.6 on 2018-09-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='hinges',
        ),
        migrations.AddField(
            model_name='line_item',
            name='hinges',
            field=models.CharField(blank=True, choices=[('LR', 'Left/Right'), ('L', 'Left'), ('R', 'Right')], max_length=2),
        ),
    ]
