# Generated by Django 2.0.6 on 2018-09-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180920_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='height_door_knob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line_item',
            name='height_door_knob_fraction',
            field=models.FloatField(choices=[(0, ''), (0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], default=0),
        ),
    ]
