# Generated by Django 2.0.6 on 2018-09-24 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_proposal_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
