# Generated by Django 2.0.6 on 2018-09-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180924_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='door_handle_cutout',
            field=models.CharField(blank=True, choices=[('Mosca', 'Mosca'), ('Luna', 'Luna'), ('Sol', 'Sol')], max_length=5),
        ),
    ]
