# Generated by Django 2.0.6 on 2018-09-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_line_item_resaque_lframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='height_middle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line_item',
            name='height_middle_fraction',
            field=models.FloatField(choices=[(0, ''), (0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], default=0),
        ),
    ]
