# Generated by Django 2.0.6 on 2018-09-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180925_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='color',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='hinge_color',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='louver',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='stain',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tilt_rod',
        ),
        migrations.AddField(
            model_name='line_item',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='line_item',
            name='finish',
            field=models.CharField(blank=True, choices=[('Paint', 'Paint'), ('Stain', 'Stain')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='line_item',
            name='hinge_color',
            field=models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Nickel', 'Nickel'), ('White', 'White'), ('Bright White', 'Bright-White'), ('Off White', 'Off-White'), ('No Hinges', 'No Hinges'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AddField(
            model_name='line_item',
            name='stain',
            field=models.CharField(blank=True, choices=[('Ash', 'Ash'), ('Basswood', 'Basswood'), ('Knotty Alder', 'Knotty Alder'), ('Maple', 'Maple'), ('Pine', 'Pine')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='line_item',
            name='tilt_rod',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Side and Back', 'Side and Back'), ('Aluminum', 'Aluminum')], max_length=15),
        ),
    ]
