# Generated by Django 2.0.6 on 2018-09-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180925_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='louver',
            field=models.FloatField(blank=True, choices=[(2.5, '2 1/2'), (3.5, '3 1/2'), (4.5, '4 1/2')], null=True),
        ),
    ]
