# Generated by Django 2.0.6 on 2018-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_line_item_louver'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='t_post',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
