# Generated by Django 2.0.6 on 2018-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_proposal_add_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='down_payment',
        ),
        migrations.AddField(
            model_name='proposal',
            name='order_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='order_down_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='order_subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='order_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='order_total',
            field=models.FloatField(default=0),
        ),
    ]
