# Generated by Django 2.0.6 on 2018-10-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20181001_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='frame_type',
            field=models.CharField(blank=True, choices=[('LF 3/4', 'LF 3/4'), ('LF 1"', 'LF 1"')], max_length=10),
        ),
    ]
