# Generated by Django 2.0.6 on 2018-07-13 23:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('home_phone', models.CharField(blank=True, max_length=25)),
                ('mobile_phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(choices=[('MX', 'MX'), ('US', 'US')], max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('home_phone', models.CharField(blank=True, max_length=25)),
                ('mobile_phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='product_finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_type', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'product_finish',
            },
        ),
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=3, unique=True)),
                ('model_description', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.product')),
            ],
            options={
                'db_table': 'product_model',
            },
        ),
        migrations.CreateModel(
            name='product_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_sqft', models.IntegerField()),
                ('product_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.product_finish')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.product_model')),
            ],
            options={
                'db_table': 'product_price',
            },
        ),
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, unique=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.product')),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField()),
                ('agents', models.ManyToManyField(to='proposal.agent')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.customer')),
                ('measured_by', models.ManyToManyField(related_name='proposal_measured_by', to='proposal.agent')),
            ],
            options={
                'db_table': 'proposal',
            },
        ),
        migrations.CreateModel(
            name='proposal_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('product_color', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('louver', models.IntegerField(choices=[(2.5, '2 1/2'), (3.5, '3 1/2'), (4.5, '4 1/2')], null=True)),
                ('panels', models.IntegerField(null=True)),
                ('int_ext', models.CharField(blank=True, choices=[('Int', 'Interior'), ('Ext', 'Exterior')], max_length=3)),
                ('trim', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('trim_type', models.CharField(blank=True, choices=[('Colonial', 'Colonial'), ('Flat', 'Flat'), ('Modern', 'Modern')], max_length=25)),
                ('tilt_rod', models.CharField(blank=True, choices=[('Aluminum', 'Aluminum'), ('Front', 'Front'), ('Side and Back', 'Side and Back')], max_length=25)),
                ('hinges', models.CharField(blank=True, choices=[('LR', 'Left/Right'), ('L', 'Left'), ('R', 'Right')], max_length=2)),
                ('hinge_color', models.CharField(blank=True, max_length=100)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('height_center', models.IntegerField(null=True)),
                ('height_left', models.IntegerField(null=True)),
                ('height_right', models.IntegerField(null=True)),
                ('approved', models.NullBooleanField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.product')),
                ('product_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.product_finish')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.product_model')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.product_type')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal.proposal')),
            ],
            options={
                'db_table': 'proposal_item',
            },
        ),
        migrations.AddField(
            model_name='product_model',
            name='product_finish',
            field=models.ManyToManyField(through='proposal.product_price', to='proposal.product_finish'),
        ),
    ]
