# Generated by Django 2.0.6 on 2018-09-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
