# Generated by Django 2.0.6 on 2018-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal_item',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='height_center',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='height_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='height_right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='louver',
            field=models.FloatField(choices=[(2.5, '2 1/2'), (3.5, '3 1/2'), (4.5, '4 1/2')], null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
