# Generated by Django 2.0.6 on 2018-09-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_proposal_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='height_center_fraction',
            field=models.FloatField(blank=True, choices=[(0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], null=True),
        ),
        migrations.AddField(
            model_name='line_item',
            name='height_fraction',
            field=models.FloatField(blank=True, choices=[(0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], null=True),
        ),
        migrations.AddField(
            model_name='line_item',
            name='height_left_fraction',
            field=models.FloatField(blank=True, choices=[(0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], null=True),
        ),
        migrations.AddField(
            model_name='line_item',
            name='height_right_fraction',
            field=models.FloatField(blank=True, choices=[(0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], null=True),
        ),
        migrations.AddField(
            model_name='line_item',
            name='width_fraction',
            field=models.FloatField(blank=True, choices=[(0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], null=True),
        ),
    ]
