# Generated by Django 2.0.6 on 2018-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_auto_20180714_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal_item',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='height_center',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='height_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='height_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='louver',
            field=models.FloatField(blank=True, choices=[(2.5, '2 1/2'), (3.5, '3 1/2'), (4.5, '4 1/2')], null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='panels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='trim',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
        migrations.AlterField(
            model_name='proposal_item',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
