# Generated by Django 2.0.6 on 2018-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20180906_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_item',
            name='height_center_fraction',
            field=models.FloatField(choices=[(0, ''), (0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], default=0),
        ),
        migrations.AlterField(
            model_name='line_item',
            name='height_fraction',
            field=models.FloatField(choices=[(0, ''), (0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], default=0),
        ),
        migrations.AlterField(
            model_name='line_item',
            name='height_left_fraction',
            field=models.FloatField(choices=[(0, ''), (0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], default=0),
        ),
        migrations.AlterField(
            model_name='line_item',
            name='height_right_fraction',
            field=models.FloatField(choices=[(0, ''), (0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], default=0),
        ),
        migrations.AlterField(
            model_name='line_item',
            name='width_fraction',
            field=models.FloatField(choices=[(0, ''), (0.125, '1/8'), (0.25, '1/4'), (0.375, '3/8'), (0.5, '1/2'), (0.625, '5/8'), (0.75, '3/4'), (0.875, '7/8')], default=0),
        ),
    ]
