# Generated by Django 2.0.6 on 2018-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20180907_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='pending',
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10),
        ),
    ]
