# Generated by Django 2.0.6 on 2018-09-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_auto_20180910_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_item',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='line_item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='line_item',
            name='separate_parts',
        ),
        migrations.RemoveField(
            model_name='line_item',
            name='t_post',
        ),
    ]
