# Generated by Django 2.0.6 on 2018-09-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20180917_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_item',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line_item',
            name='height_center',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line_item',
            name='height_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line_item',
            name='height_right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line_item',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
