# Generated by Django 2.0.6 on 2018-09-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_auto_20180917_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_item',
            old_name='price',
            new_name='price_per_sq_ft',
        ),
        migrations.AddField(
            model_name='line_item',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
